org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
neo_version=21.1.248
ftb_quests_version=2101.1.30
ftb_library_version=2101.1.35
ftb_teams_version=2101.1.10
architectury_version=13.0.11

mod_id=afterlight
mod_name=AFTERLIGHT Signal
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=org.rllabs.afterlight
