modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="afterlight"
version="0.2.0"
displayName="AFTERLIGHT Signal"
authors="RLLabs"
description='''
The Signal companion mod for AFTERLIGHT.
'''

[[dependencies.afterlight]]
modId="neoforge"
type="required"
versionRange="[21.1.248]"
ordering="NONE"
side="BOTH"

[[dependencies.afterlight]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.afterlight]]
modId="ftbquests"
type="required"
versionRange="[2101.1.30]"
ordering="AFTER"
side="BOTH"

[[dependencies.afterlight]]
modId="ftblibrary"
type="required"
versionRange="[2101.1.35]"
ordering="AFTER"
side="BOTH"

[[dependencies.afterlight]]
modId="ftbteams"
type="required"
versionRange="[2101.1.10]"
ordering="AFTER"
side="BOTH"
